SELECT
	IDASSEVENTO,
	EVENTO_COD,
	EVT_DES AS EVENTO_DESCRIZIONE,
	(SELECT COUNT(EVTCC_NDOC) FROM SALOP.EVTCCCC A WHERE A.EVTCC_PAP = B.EVTCC_NDOC AND ROWNUM<2) AS HAFIGLI,
	EVTCC_STATO AS STATO_COD,
	STATO_DESCR AS STATO_DESCRIZIONE,
	EVTCC_DATA AS DATA_CREAZIONE,
	EVTCC_PAP AS IDASSEVENTO_PADRE,
	REPARTO_COD,
	NVL(REP_DESC,'REPARTO NON DECODIFICABILE') AS REPARTO_DESCRIZIONE
FROM 
	(
	SELECT
		EVTCC_NDOC AS IDASSEVENTO,
		EVTCC_COD AS EVENTO_COD,
		EVTCC_EMI AS REPARTO_COD,
		LEVEL 
	FROM EVTCCCC 
	START WITH 
    --EVTCC_NDOC = :IDASSEVENT 
    EVTCC_PAP IS NULL
    AND EVTCC_OBSO ='0'
	CONNECT BY PRIOR EVTCC_NDOC = EVTCC_PAP
	),
	EVTCCCC B,
	SALOP.EVTCS,
	SALOP.EVT_STATO,
	SALOP.DSANAREP
WHERE
	EVT_COD = EVTCC_COD
	AND EVTCC_NDOC = IDASSEVENTO
	AND EVTCC_OBSO = '0'
	AND STATO_COD=EVTCC_STATO
	AND REP_CINT(+) = EVTCC_EMI
ORDER BY
	DECODE (EVENTO_COD, 1, -200, EVTCC_ORD), EVTCC_DATA