CREATE OR REPLACE PROCEDURE SALOP.EVTCCCC_TREE
  (
    p_idassevento_radice IN NUMBER,
    p_recordset OUT SYS_REFCURSOR
  )
IS
BEGIN
  OPEN p_recordset FOR 
  SELECT
    EVTCC_NDOC AS IDASSEVENTO,
    EVTCC_PAP AS IDASSPADRE,
    DECODE(CONNECT_BY_ISLEAF, 1, 0, 0, 1) AS HAFIGLI,
    LEVEL,
    EVTCC_COD AS EVENTO_COD,
    EVT_DES AS EVENTO_DESCRIZIONE,
    EVTCC_EMI AS REPARTO_COD,
    NVL(DSANAREP.REP_DESC,'REPARTO NON DECODIFICABILE') AS REPARTO_DESCRIZIONE,
    EVT_STATO.STATO_COD,
    EVT_STATO.STATO_DESCR AS STATO_DESCRIZIONE,
    EVTCC_DATA AS DATA_CREAZIONE
  FROM EVTCCCC, EVTCS, DSANAREP, EVT_STATO
  WHERE 
    EVTCS.EVT_COD = EVTCCCC.EVTCC_COD
    AND EVTCCCC.EVTCC_EMI = DSANAREP.REP_CINT(+)
    AND EVTCCCC.EVTCC_STATO = EVT_STATO.STATO_COD
  START WITH
    EVTCC_NDOC = p_idassevento_radice
    AND EVTCC_OBSO ='0'
  CONNECT BY 
    PRIOR EVTCC_NDOC = EVTCC_PAP
    AND EVTCC_OBSO ='0'
  ORDER SIBLINGS BY DECODE (EVENTO_COD, 1, -200, EVTCS.EVT_ORD), EVTCC_DATA;
END;

