SELECT ANPRE_ANNO,
  ANPRE_PAZ,
  ANPRE_IDASS,
  ANPRE_NMT,
  ANPRE_ANAMDES,
  ANPRE_OP,
  ANPRE_DATA,
  ANPRE_OPOP,
  ANPRE_DADA,
  ANPRE_OBSO,
  ANPRE_IDRIGA,
  ANPRE_ANAMMEM
FROM EVTANPRE 
WHERE 
  -- ANPRE_PAZ = '68005729'
  -- ANPRE_PAZ = 'TX9057416'
  ANPRE_PAZ = 'TX9057443'
ORDER BY ANPRE_DATA DESC
;