select * from  (
SELECT 
TO_CHAR(ERR_DATA, 'YY-MM-DD HH:MI:SS'),
ERR_USERNAME,
  ERR_MESSAGGIO,
  ERR_MESSAGGIO_NUM,
  ERR_STACK,
  ERR_IPMACCHINA,
  ERR_DATA,
  ERR_IDMODULO,
  ERR_FLAG,
  ERR_VERSION
FROM DSHOP.GEAUTERR
WHERE ERR_IDMODULO = 'CC-Web'
ORDER BY ERR_DATA DESC
)
WHERE ROWNUM <= 50;